Listen 3000
ServerName localhost

<VirtualHost *:3000>
    DocumentRoot /workspace/public
    DirectoryIndex index.cgi
    PassEnv DB_HOST DB_PORT DB_NAME DB_USER DB_PASSWORD

    <Directory /workspace/public>
        Options +ExecCGI
        AddHandler cgi-script .cgi
        Require all granted
    </Directory>

    ErrorLog /proc/self/fd/2
    CustomLog /proc/self/fd/1 combined
</VirtualHost>
